# Generated by Django 2.1.5 on 2020-06-17 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0002_auto_20200617_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dadospaciente',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.Medico', verbose_name='Nome Medico'),
        ),
        migrations.AddField(
            model_name='dadospaciente',
            name='nm_medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.Farm_medicamentos'),
        ),
        migrations.AddField(
            model_name='dadospaciente',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.Nome_paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='dadospaciente',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
