# Generated by Django 2.1.5 on 2020-06-17 04:01

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Cliente')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('dt_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
