# Generated by Django 2.0.6 on 2020-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Cliente'),
        ),
    ]
