# Generated by Django 2.0.6 on 2020-06-06 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgeo', '0003_auto_20200606_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
