# Generated by Django 2.0.6 on 2018-07-12 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nr_cpf_cgc', models.CharField(max_length=11, verbose_name='CPF')),
                ('ds_codigo_conselho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código do Conselho')),
                ('foto_perfil', models.FileField(upload_to=usuarios.models.foto_perfil_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
