# Generated by Django 2.0.6 on 2018-07-13 14:37

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to=usuarios.models.foto_perfil_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nm_completo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nr_cpf_cgc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
