# Generated by Django 2.0.6 on 2018-07-13 15:49

import core.helpers
from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180713_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.foto_perfil_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nr_cpf_cgc',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[core.helpers.validate_CPF], verbose_name='CPF'),
        ),
    ]
