# Generated by Django 2.0.6 on 2020-06-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180713_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.IntegerField(default=0),
        ),
    ]
