# Generated by Django 2.0.6 on 2020-06-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_userprofile_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
