# Generated by Django 2.1.5 on 2020-06-17 04:01

import core.helpers
from django.db import migrations, models
import prestadores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_especialidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorPessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Validação'), ('VALIDADO', 'Validado (Ativo)'), ('INVALIDO', 'Inválido'), ('INATIVO', 'Inativo')], default='PENDENTE', max_length=30)),
                ('cd_prestador', models.IntegerField(blank=True, null=True)),
                ('sn_cuidador', models.NullBooleanField(verbose_name='Cuidador?')),
                ('nm_prestador', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nr_cpf_cgc', models.CharField(max_length=11, validators=[core.helpers.validate_CPF], verbose_name='CPF')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nm_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('nm_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai')),
                ('ds_codigo_conselho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código do Conselho')),
                ('ds_faculdade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Faculdade')),
                ('ds_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('nr_cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('ds_endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('ds_complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('ds_bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('nm_cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('cd_uf', models.CharField(blank=True, max_length=200, null=True, verbose_name='UF')),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('ds_agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência Bancária')),
                ('nr_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Bancária')),
                ('nr_fone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para Contato')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('identidade_frente', models.FileField(upload_to=prestadores.models.identidade_frente_directory_path, validators=[core.helpers.validate_file_extension])),
                ('identidade_verso', models.FileField(upload_to=prestadores.models.identidade_verso_directory_path, validators=[core.helpers.validate_file_extension])),
                ('comprovante_residencia', models.FileField(upload_to=prestadores.models.comp_resid_directory_path, validators=[core.helpers.validate_file_extension])),
                ('especialidades', models.ManyToManyField(to='prestadores.Especialidade')),
            ],
            options={
                'verbose_name_plural': 'prestadores',
            },
        ),
    ]
