# Generated by Django 2.0.6 on 2018-07-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0002_prestadorpessoafisica_nm_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestadorpessoafisica',
            name='nm_completo',
        ),
    ]
