# Generated by Django 2.0.6 on 2018-07-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0003_remove_prestadorpessoafisica_nm_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestadorpessoafisica',
            old_name='user',
            new_name='usuario',
        ),
    ]
