# Generated by Django 2.0.6 on 2018-07-13 17:18

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestadores', '0004_auto_20180712_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestadorpessoafisica',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='nr_cpf_cgc',
            field=models.CharField(max_length=11, validators=[core.helpers.validate_CPF], verbose_name='CPF'),
        ),
    ]
