# Generated by Django 2.0.6 on 2018-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0005_auto_20180713_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestadorpessoafisica',
            name='comprovante_cnpj',
        ),
        migrations.RemoveField(
            model_name='prestadorpessoafisica',
            name='nm_tip_presta',
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado'), ('INATIVO', 'Inativo')], default='PENDENTE', max_length=30),
        ),
    ]
