# Generated by Django 2.0.6 on 2018-07-14 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0006_auto_20180713_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
