# Generated by Django 2.0.6 on 2018-07-14 16:58

import core.helpers
from django.db import migrations, models
import prestadores.models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0007_auto_20180714_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='comprovante_residencia',
            field=models.FileField(upload_to=prestadores.models.comp_resid_directory_path, validators=[core.helpers.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='identidade_frente',
            field=models.FileField(upload_to=prestadores.models.identidade_frente_directory_path, validators=[core.helpers.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='identidade_verso',
            field=models.FileField(upload_to=prestadores.models.identidade_verso_directory_path, validators=[core.helpers.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Validação'), ('VALIDADO', 'Validado (Ativo)'), ('INVALIDO', 'Inválido'), ('INATIVO', 'Inativo')], default='PENDENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
