# Generated by Django 2.0.6 on 2018-07-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0009_auto_20180714_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='nr_cpf_cgc',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
