# Generated by Django 2.0.6 on 2018-07-15 17:35

import core.helpers
from django.db import migrations, models
import prestadores.models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0010_auto_20180714_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='comprovante_residencia',
            field=models.FileField(upload_to=prestadores.models.comp_resid_directory_path, validators=[core.helpers.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='identidade_frente',
            field=models.FileField(upload_to=prestadores.models.identidade_frente_directory_path, validators=[core.helpers.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='identidade_verso',
            field=models.FileField(upload_to=prestadores.models.identidade_verso_directory_path, validators=[core.helpers.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prestadorpessoafisica',
            name='nr_cpf_cgc',
            field=models.CharField(max_length=11, validators=[core.helpers.validate_CPF], verbose_name='CPF'),
        ),
    ]
