# Generated by Django 2.0.6 on 2020-04-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0012_auto_20200412_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterModelOptions(
            name='prestadorpessoafisica',
            options={'verbose_name_plural': 'prestadores'},
        ),
    ]
