# Generated by Django 2.0.6 on 2020-04-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0014_auto_20200420_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergia', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='alergia',
            field=models.NullBooleanField(verbose_name='Alergico?'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='altura',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='convenio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Convênio'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='doenca_base',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doença Base'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='frequencia_cardiaca',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Frequencia Cardiaca'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='glicemia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Glicemia'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='horarios_medicacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Horario Medicação'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='hospital_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hospital de Referência'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='medicamento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='medico_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Medico Responsável'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='nivel_alergia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nivel Alergia'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='peso',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='temperatura',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='prestadorpessoafisica',
            name='tipo_alergia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Alergia'),
        ),
    ]
