# Generated by Django 2.0.6 on 2020-04-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0015_auto_20200420_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alergia',
        ),
    ]
